export const APP_ROUTES = {
  SIGN_UP: '/signup',
  SIGN_IN: '/signin',
  SEARCH_PAGE: '/searchpage',
  HOME_PAGE: '/homepage',
  CART_PAGE: '/cart',
  ADRESS: '/adress',
  PRODUCT: '/product',
  ABOUT_US: '/aboutus',
  ADRESSUPDATE: '/addressupdate',
  MY_ORDERS: '/pedidos',
  CONTACT: '/contact',
  CARDS: '/cards',
  SUCCESS: '/sucesso',
  FAILURE: '/erro',
  PENDING: '/pendente',
  ACADEMIA: '/academia',
  BASQUETE: '/basquete',
  CICLISMO: '/ciclismo',
  FUTEBOL: '/futebol',
  LUTA: '/luta',
  NATACAO: '/natacao',
  VOLEIBOL: '/voleibol',
  VARIADOS: '/variados',
  TODOS: '/todos'
};
